# Site settings
title: Russell Brown
email: RussellBrownCompany@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the website of Russell Brown. I'm a website and app developer
  from Southern Illinois. I'm also into photography and old cars!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rwbrown72.github.io" # the base hostname & protocol for your site
twitter_username: russellbrownco
github_username:  rwbrown72

# Build settings
markdown: kramdown
